<?php

/**
 * @file
 * CTools primary module file.
 *
 * @todo Description.
 */

// Voir : https://gist.github.com/1979037
// Voir : http://awebfactory.com.ar/node/491
// Voir : http://www.spsc.uniroma1.it/sites/all/modules/ctools/help/modal.html

// ---------------------------------------------------------------------------
// Drupal hooks.

/**
 *  Implements hook_menu()
 */
function modal_bundle_add_menu() {
  $items['modal_bundle_add_test_page'] = array(
    'title' => 'tEST',
    'page callback' => 'modal_bundle_add_test_page',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['modal_bundle_add/%ctools_js/add'] = array(
    'title' => 'Animal',
    'page callback' => 'modal_bundle_add_test',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/*
 * Implements hook_field_widget_form_alter().
 */
function modal_bundle_add_field_widget_form_alter(&$element, &$form_state, $context) {
  // For performance reasons, If there are several fields "entityreference", these variables were declared static
  static $arg_modal_bundle_add;
  static $add_links = FALSE;
  
  // If arg(0) != 'modal_bundle_add', then we aren't on the modal "add content"
  if (!isset($arg_modal_bundle_add)) {
    $arg_modal_bundle_add = arg(0);

    if ($arg_modal_bundle_add != 'modal_bundle_add') {
      // therefore we allow adding links "add content".
      if (!$add_links) {
        $add_links = TRUE; 
      }
    }
  }
  
  // If we can add the links "entityreference"
  if ($add_links) {  
    
    // We add that for all fields of type "entityreference".
    if ($context['field']['type'] == 'entityreference') {

  //    dsm($context);

  //  contains the bundles referenced
  //    dsm($context['field']['settings']['handler_settings']['target_bundles']);

      modal_bundle_add_library();
      
      // Include the CTools tools that we need.
//      ctools_include('ajax');
//      ctools_include('modal');

      // Add CTools' javascript to the page.
//      ctools_modal_add_js();

      $element['#suffix'] = '<div>' . ctools_modal_text_button(t('Add content'), 'modal_bundle_add/nojs/add', t('Pick an animal')) . '</div>';
    }
  }
}

// ---------------------------------------------------------------------------
// Page callbacks

/**
 * Page callback to display links and render a container for AJAX stuff.
 */
function modal_bundle_add_test_page() {
  global $user;

  // Include the CTools tools that we need.
  ctools_include('ajax');
  ctools_include('modal');

  // Add CTools' javascript to the page.
  ctools_modal_add_js();

  // Create a list of clickable links.
  $links = array();

  // Four ways to do our animal picking wizard.
  $links[] = ctools_modal_text_button(t('Wizard (default modal)'), 'modal_bundle_add/nojs/add', t('Pick an animal'));

  $output = theme('item_list', array('items' => $links, 'title' => t('Actions')));

  return array('markup' => array('#markup' => $output));
}

/**
 * A modal login callback.
 */
function modal_bundle_add_test($js = NULL) {
  global $user;
  
  // Fall back if $js is not set.
  if (!$js) {
    return "javascript required";
//    return drupal_get_form('article');
  }  

  // Include your ctools crap here
//  ctools_include('node.pages', 'node', '');
  module_load_include('inc', 'node', 'node.pages');
  ctools_include('modal');
  ctools_include('ajax');

 // Create a blank node object here. You can also set values for your custom fields here as well.
  $node = (object) array(
    'uid' => $user->uid,
    'name' => (isset($user->name) ? $user->name : ''),
    'type' => 'article',
//    'language' => LANGUAGE_NONE,
    'language' => $user->language,
  );

  $form_state = array(
  'title' => t('Login'),
//  'ajax' => $js,
  'ajax' => TRUE,
  );
  $form_state['build_info']['args'] = array($node);

  $output = ctools_modal_form_wrapper('article_node_form', $form_state);

  if (!empty($form_state['executed'])) {
    // We'll just overwrite the form output if it was successful.
    $output = array();
    $output[] = ctools_modal_command_display(t('Success'), '<div class="modal-message">Successful</div>');
    // Close the modal
//    $output[] = ctools_modal_command_dismiss();
  }

  print ajax_render($output);
  exit;


//  ctools_include('modal');
//  ctools_include('ajax');
//
//  ctools_modal_render('Disneyland', 'mickey');
//  $commands = array('mickey');
}

// ---------------------------------------------------------------------------
// Functions

/**
 * Adds all the JS/Ajax libraries for the modal to the page.
 */
function modal_bundle_add_library() {
  static $included = FALSE;

  if (!$included) {
    $included = TRUE;

    if (module_exists('ctools')) {
      ctools_include('ajax');
      ctools_include('modal');
      ctools_modal_add_js();
    }
  }
}